### PR TITLE
Fix/language detector not working

### LINKED ISSUE #12: Issuer is untranslated
Although the issuer appears to have two locales they both have the Dutch language, also there is no way of controlling the locale for now.

https://github.com/privacybydesign/irma_idin_issuer/blob/57cc61192a88e7aaa9e1b255b9a18afe86f9a0ec/frontend/src/languages/en.json#L2-L4

https://github.com/privacybydesign/irma_idin_issuer/blob/57cc61192a88e7aaa9e1b255b9a18afe86f9a0ec/frontend/src/languages/nl.json#L2-L4

### PR DESCRIPTION
**Pull request by rutgerth1508**
Fixes #12

### CODE REVIEW

File: src/main/java/org/irmacard/idin/web/IdinResource.java [hunk 1]
```diff
@@ -243,6 +242,24 @@ private static Response upstreamError(final String description, final String mes
                 .build();
     }
 
+    private String getDescriptionBankUnavailable(final String acceptLanguage) {
```
Comment (w-ensink) [inline src/main/java/org/irmacard/idin/web/IdinResource.java]: Can these be part of the i18n config?

Comment (rutgerth1508) [reply src/main/java/org/irmacard/idin/web/IdinResource.java]: I have added them to it

**Review by DibranMulder — APPROVED** [review]
